### ISSUE TITLE
En tant qu'utilisateur, je souhaite m'authentifier à travers l'API

### ISSUE THREAD

**Issue by Meknassih** [RayZiaX/APINodeJs#2]
Je dois pouvoir m'authentifier en envoyant une requête **POST** sur `/authenticate` avec un corps de requête (body) de la forme : 
```
{
  "username": "chainedecaracteres",
  "password": "chainedecaracteres"
}
```

**Comment by RayZiaX** [comment]
Closed by: ed22c29d4e2c348960fb350caa266e33565925b3
