### ISSUE TITLE
En tant qu'utilisateur, je souhaite pouvoir connaître le statut de l'API

### ISSUE THREAD

**Issue by Meknassih** [RayZiaX/APINodeJs#3]
Je dois pouvoir envoyer une requête **GET** sur `/` pour obtenir le statut actuel de l'API de la forme: 
```
{
  "version": 0.1.0
  "status": [0, 1]
}
```

**Comment by RayZiaX** [comment]
Issue close f7c927f56106a18acb27f78ebad46a628423ce32
