### ISSUE TITLE
En tant qu'utilisateur, je souhaite pouvoir récupérer tous les utilisateurs inscrits

### ISSUE THREAD

**Issue by Meknassih** [RayZiaX/APINodeJs#4]
Je dois pouvoir faire une requête **GET** sur `/users` pour obtenir tous les utilisateurs existants sous forme d'un tableau d'objets:
```
[
  {
    "id": 1,
    "username": "abc",
    "firstname": "prenom",
     ...
  },
  ...
]
```

**Comment by RayZiaX** [comment]
Issue closed 7537ac4b5e852bc5826618330daa2b8c6c3c2d51
